name: Docker Image Hardening

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image with Security Best Practices
      run: |
        docker build --no-cache -t myapp:latest .
        docker run --rm --cap-drop=ALL --cap-add=NET_BIND_SERVICE myapp

    - name: Scan Image for Vulnerabilities
      run: |
        trivy image myapp:latest

    - name: Push to Docker Hub
      run: |
        docker tag myapp:latest mydockerhub/myapp:latest
        docker push mydockerhub/myapp:latest
